# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlusers',
            name='db',
        ),
        migrations.AddField(
            model_name='mysqlusers',
            name='instance',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='databases.Instances'),
        ),
    ]
