# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20180731_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlusers',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.Instances'),
        ),
    ]
