# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-31 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_auto_20180731_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privileges',
            unique_together=set([('user', 'instance', 'db')]),
        ),
    ]
